name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      release-version: 
        description: "What's next version? (e.g., 1.0.0)"
        required: true
        type: string
      pre-release:
        type: boolean
        default: true
      description:
        description: "Package description"
        required: false
        type: string
        default: "An unofficial .NET SDK for https://omg.lol API service."

permissions:
  contents: write

jobs:
  bump-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name : Increment assembly to version ${{ github.event.inputs.release-version }}
        id: version-bump
        uses: Thundernerd/dotnet-project-version-updater@v1.2
        with:
          file: "./Omg.Lol.Net/Omg.Lol.Net.csproj"
          version: ${{ github.event.inputs.release-version }}

      - name: Commit version bump and tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.csproj'
          commit_message: "[CI commit] Bump from version ${{steps.version-bump.outputs.oldVersion}} to ${{steps.version-bump.outputs.newVersion}}"
          tagging_message: ${{ steps.version-bump.outputs.newVersion }}
          create_branch: false

      - name: Checkout new tag
        run: git pull --prune && git checkout ${{ steps.version-bump.outputs.newVersion }}

      - name: Dotnet package
        run: 'dotnet pack 
              -c Release 
              /p:Descriptoin="${{github.event.inputs.description }}" 
              -o . 
              ./Omg.Lol.Net/Omg.Lol.Net.csproj'

      - name: See what ref is
        run: echo "${{ github.ref }}"

      - name: Drop to Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(${{ github.ref }}, 'refs/tags/') # only works in a tag
        with:
          prerelease: ${{ github.event.inputs.pre-release }}
          files: |
            *.nupkg
            LICENSE
