name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      release-version: 
        description: "What's next version? (e.g., 1.0.0)"
        required: true
        type: string
      pre-release:
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  bump-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name : Increment assembly to version ${{ github.event.inputs.release-version }}
        id: version-bump
        uses: Thundernerd/dotnet-project-version-updater@v1.2
        with:
          file: "./Omg.Lol.Net/Omg.Lol.Net.csproj"
          version: ${{ github.event.inputs.release-version }}

      - name: Commit version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.csproj'
          commit_message: "[CI commit] Bump from version ${{steps.version-bump.outputs.oldVersion}} to ${{steps.version-bump.outputs.newVersion}}"
          create_branch: false

      - name: Dotnet package
        run: 'dotnet pack 
              -c Release 
              -o . 
              ./Omg.Lol.Net/Omg.Lol.Net.csproj'

      - name: Tag & Drop to Github Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.event.inputs.pre-release }}
          files: "*.nupkg"
          tag_name: v${{ steps.version-bump.outputs.newVersion }}
          fail_on_unmatched_files: true
          generate_release_notes: true
