name: Integration Test

on: 
 workflow_dispatch:
 pull_request:
   branches:
    - main

jobs:
  Baseline:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-2019, windows-2022, macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install .NET SDK 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install .NET SDK 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Check dotnet version
        run: dotnet --list-sdks
      
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Build
        run: dotnet build -c Release ./Omg.Lol.Net.sln
        
      - name: Test
        env:
          OMG_LOL_MYSTERIOUS_API_KEY: ${{ secrets.OMG_LOL_MYSTERIOUS_API_KEY }}
        run: dotnet test -c Release --no-build ./Omg.Lol.Net.sln
    
