name: SDK Build & Test (Prod)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-And-Test:
    strategy:
      matrix:
        os: [ubuntu-22.04] #, ubuntu-20.04, windows-2019, windows-2022, macos-12, macos-11]
        dotnet-version: ['6.0.x'] #, '7.0.x']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          dotnet-quality: validated
          
      - name: Check dotnet version
        run: dotnet --version
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: dotnet build -c Release ./Omg.Lol.Net.sln
        
      - name: Test
        run: dotnet test -c Release ./Omg.Lol.Net.sln
    
